services:
  blogify-backend:
    build:
      context: .
    container_name: blogify-backend
    ports:
      - "8000:8000"  
    command: ["gunicorn", "blog.wsgi:application", "--bind", "0.0.0.0:8000", "--timeout", "30"]
    

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  
    ports:
      - "80:80" 
    depends_on:
      - blogify-backend