version: '3.8'

services:
  blogify-backend:
    build:
      context: .
    container_name: blogify-backend
    expose:
      - "8000" 

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  
    ports:
      - "80:80" 
    depends_on:
      - blogify-backend