# Generated by Django 5.1.3 on 2024-11-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='upvote',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
