# Generated by Django 5.1.3 on 2024-12-02 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_blog_upvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='upvote',
        ),
    ]
