# Generated by Django 5.1.3 on 2024-12-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_remove_blog_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='upvote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
